model:
  name: ppo_pfrl
  train_model: True
  test_model: False
  load_model: False
  run_model: True
  graphic: False
  vehicle_max: 1
  learning_rate: 0.0001
  batch_size: 64
  gamma: 0.95
  epsilon: 0.1
  epsilon_decay: 0.995
  epsilon_min: 0.01
  grad_clip: 5.0
  NEIGHBOR_NUM: 4
  NEIGHBOR_EDGE_NUM: 4
  one_hot: True
  phase: True

trainer:
  learning_start: 5000
  buffer_size: 5000
