trainer:
  episodes: 5

sim2real:
  method: domain_randomization
  load_pretrained: True
  domain_randomization:
    enabled: True
    seed: 0
    parameters:
      detection_zone_distance:
        path: ["detection_zone", "distance_m"]
        distribution: uniform
        uniform_config:
          low: 100000
          high: 100000
      noise_lambda:
        path: ["noise", "poisson_config", "lambda"]
        distribution: uniform
        uniform_config:
          low: 5.0
          high: 5.0
      lane_failure_probability:
        path: ["disable_sensor", "lane_level", "probability"]
        distribution: uniform
        uniform_config:
          low: 0.0
          high: 0.5
      intersection_failure_probability:
        path: ["disable_sensor", "intersection_level", "probability"]
        distribution: uniform
        uniform_config:
          low: 0.0
          high: 0.0
