includes:
  - configs/sim2real_transitions/base.yml

sim2real:
  method: grounding
  gattype: "decentralized"
  uncertainty: True
  delayedgat: False
  ground_original: False
  training_iterations: 1
  last_n_uncertainties: 2
