sim2real:
  transform_seed: 0
  detection_zone:
    enabled: False
    distance_m: 100
  noise:
    enabled: True
    features: ["lane_count", "lane_waiting_count", "lane_waiting_time_count", "lane_delay"]
    probability: 1.0
    distribution: poisson # gaussian, poisson
    gaussian_config:
      mean: 0.0
      std: 1.0
      relative: False
    poisson_config:
      lambda: 5.0
      rate: 1.0
      centered: False
      relative: False
    bias: 0.0
    scale: 1.0
    clip_min: 0.0
    clip_max:
    round: False
    cast_int: False
  disable_sensor:
    enabled: True
    features: ["lane_count", "lane_waiting_count", "lane_waiting_time_count", "lane_delay"]
    mask_mode: episode # run, episode, step
    fill_value: 0.0
    lane_level:
      enabled: True
      probability: 0.5
    intersection_level:
      enabled: False
      probability: 1.0
