from .base import NonRLAgent
from common.registry import Registry
from generator import LaneVehicleGenerator, IntersectionPhaseGenerator, IntersectionVehicleGenerator
import numpy as np
import gym

@Registry.register_model('fixedtime')
class FixedTimeAgent(NonRLAgent):
    '''
    FixedTimeAgent gives a predefined time duration and phase order.
    '''
    def __init__(self, world, rank):
        super().__init__(world)
        self.world = world
        self.rank = rank
        self.model = None

        # get generator for each MaxPressure
        self.id = self.world.intersection_ids[self.rank]
        self._build_generators()

        self.action_space = gym.spaces.Discrete(len(self.inter_obj.phases))
        # dirrerent datasets have the same t_fixed
        self.t_fixed = Registry.mapping['model_mapping']['setting'].param['t_fixed']

    def __repr__(self):
        return 'FixedTime Agent has no Network model'

    def _build_generators(self):
        '''
        _build_generators
        (Re)build every generator this agent reads. Shared by __init__ and reset so
        the two cannot drift apart.

        :param: None
        :return: None
        '''
        self.ob_generator = LaneVehicleGenerator(self.world, self.inter_obj, ['lane_count'], in_only=True, average=None)
        self.phase_generator = IntersectionPhaseGenerator(self.world, self.inter_obj, ["phase"],
                                                          targets=["cur_phase"], negative=False)
        self.reward_generator = LaneVehicleGenerator(self.world, self.inter_obj, ["lane_count"],
                                                     in_only=True, average='all', negative=True)

        self.queue = LaneVehicleGenerator(self.world, self.inter_obj,
                                                     ["lane_waiting_count"], in_only=True,
                                                     negative=False)

        self.delay = LaneVehicleGenerator(self.world, self.inter_obj,
                                                     ["lane_delay"], in_only=True,
                                                     negative=False)

    def reset(self):
        '''
        reset
        Reset information, including ob_generator, phase_generator, queue, delay, etc.

        :param: None
        :return: None
        '''
        self._build_generators()

    def get_ob(self):
        '''
        get_ob
        Get observation from environment.

        :param: None
        :return x_obs: observation generated by ob_generator
        '''
        x_obs = []
        x_obs.append(self.ob_generator.generate())
        x_obs = np.array(x_obs, dtype=np.float32)
        return x_obs

    def get_reward(self):
        '''
        get_reward
        Get reward from environment.

        :param: None
        :return rewards: rewards generated by reward_generator
        '''
        rewards = []
        rewards.append(self.reward_generator.generate())
        rewards = np.squeeze(np.array(rewards)) * 12
        return rewards
    
    # get_phase() is inherited from NonRLAgent: it reads the LIVE intersection
    # instead of phase_generator, whose cached Intersection goes stale on sumo.
    
    def get_action(self, ob, phase, test=True, valid_mask_fn=None):
        '''
        get_action
        Generate action. Note `ob` is ignored by construction: a fixed-time plan
        cycles on a timer and never reads a detector, so it is structurally immune
        to the observation gap (that invariance is a result, not a bug).

        :param ob: observation (unused)
        :param phase: current phase
        :param test: boolean, decide whether is test process
        :param valid_mask_fn: optional `phase -> bool mask` from the phase-transition
            transform. Under the gap (enforce) baseline this is all-permissive except
            at force-off, where holding past max-green is illegal; honoring it keeps
            this baseline's controller semantics identical to the RL agents'.
        :return action: action in the next order
        '''
        # phases: just index of self.inter_obj.phases, not green light index
        assert self.inter_obj.current_phase == phase[-1]
        cur = self.inter_obj.current_phase
        n_phases = len(self.inter_obj.phases)
        mask = self._valid_mask(valid_mask_fn, phase, n_phases)

        # Hold while the timer runs, unless the controller has masked holding out.
        if self.inter_obj.current_phase_time < self.t_fixed:
            if mask is None or mask[cur]:
                return cur
        # Advance to the next phase in cycle order that the controller will accept.
        if mask is None:
            return (cur + 1) % n_phases
        for step in range(1, n_phases + 1):
            nxt = (cur + step) % n_phases
            if mask[nxt]:
                return nxt
        # TODO(post-submission): unreachable in practice -- PhaseTransition always leaves
        # a legal successor via _forceoff_target. Drop it. notes/nonrl_cleanup_todo.md
        return (cur + 1) % n_phases  # degenerate table: keep cycling

    def get_queue(self):
        '''
        get_queue
        Get queue length of intersection.

        :param: None
        :return: total queue length
        '''
        queue = []
        queue.append(self.queue.generate())
        queue = np.sum(np.squeeze(np.array(queue)))
        return queue

    def get_delay(self):
        '''
        get_delay
        Get delay of intersection.

        :param: None
        :return: total delay
        '''
        delay = []
        delay.append(self.delay.generate())
        delay = np.sum(np.squeeze(np.array(delay)))
        return delay